### ISSUE TITLE
XSS攻撃に対して脆弱

### ISSUE THREAD

**Issue by gpsoft** [kinokomochi/memo#4]
メモのタイトルや本文にスクリプトを仕込んで保存されてしまったとき、そのメモを表示すると、XSS(クロスサイトスクリプティング)攻撃を受けてしまいます。

例えば、新規メモの本文に以下の1行を貼り付けて保存してみて下さい。
```
<script>window.location='http://yahoo.co.jp';</script>
```
showページへ遷移した瞬間に、Yahooのページへ移動すると思います。
これがXSSです。
移動先がYahooじゃなくて悪質なサイトだったら大変ですよね。

なぜ上記のような現象が起きるのか分かるでしょうか?
対策についても、調べてみて下さい。
近いうちに、フォローさせて頂きますね。

**Comment by kinokomochi** [comment]
解決
